[package]
name = "flarec"
version = "0.1.0"
edition = "2024"

[dependencies]
flare_internals = { path = "../flare_internals" }
bnf = "0.5.0"
pretty_env_logger = "0.5.0"
log = "0.4.28"

[[bin]]
name = "flarec"
bench = false