use super::{ast::SymbolKind, lexemes::Lexeme};

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum TokenKind {
    TkKWOp,
    TkKWVal,
    TkSymbol,
    TkLiteral,
    TkNumeric,
    TkTyInt,
    TkTyFlt,
    TkTyStr,
    TkTrue,
    TkFalse,
    TkTyMute,
    TkPlus,
    TkMinus,
    TkStar,
    TkSlash,
    TkLparen,
    TkRparen,
    TkSmallArr,
    TkBigArr,
    TkPipe,
    TkPercent,
    TkDoubleDot,
    TkLBrace,
    TkRBrace,
    TkStatementEnd,
    TkEqual,
    TkCEQ,
    TkCNE,
    TkCLT,
    TkCLE,
    TkCGT,
    TkCGE,
    TkAnd,
    TkOr,
    TkComma,
    TkColon,
    TkDot,
    TEof,
}

#[derive(Clone, Debug)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: Lexeme,
    pub literal: SymbolKind,
    pub location: usize,
}