[package]
name = "flare"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
colored = "2.1.0"
crustal = "0.3.5"
itertools = "0.13.0"
lazy_static = "1.4.0"
logos = "0.14.1"
ordered-float = { version = "4.5.0", features = ["serde"] }
peg = "0.8.4"
# rayon = "1.10.0"
reporting = "0.1.4"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
thiserror = "2.0.7"

[patch.crates-io]
reporting = { path = "/home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reporting-0.1.4" }


[profile.release]
opt-level = 3
strip = "symbols"
lto = "thin"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
