default: show_ir

build: 
    cargo build -p flarec

release: 
    cargo build --release -p flarec

run:
    cargo run -p flarec  -- -c examples/ntest.flr

show_ir:
    just run
    bat examples/ntest.ir    

compile path:
    cargo run -p flarec -- -c {{path}}

run-release:
    cargo run --release -p flarec -- -c examples/ntest.flr

bench:
    cargo bench --features testing -p flare_internals

test: 
    cargo test  --features testing --  --no-capture

build-profile:
    cargo build --profile bench -p flarec

profile:
    valgrind --tool=cachegrind /workspaces/allegro/flare/target/release/flarec -c /workspaces/allegro/flare/flare_internals/benches/bench_code/bench1.flr
#    rm cachegrind.*

bulk:
    #!/bin/zsh
    just build;
    while  ./target/debug/flarec -c examples/ntest.flr; do :; done

debt:
    debtmap analyze .

 
# -Zmiri-many-seeds=..100
export MIRIFLAGS := " -Zmiri-disable-isolation -Zmiri-ignore-leaks -Zmiri-many-seeds=..10"
# export RUSTFLAGS := "-Zrandomize-layout"
miri:
    cargo +nightly miri run -p flarec  -- -c examples/ntest.flr

reset:
    cargo clean
    cargo build
    cargo build --release
