//This file was automatically generated by allegro.
//Submit bug reports to https://github.com/UPWRD1/allegro

#include <stdio.h>

int test(int y) {
    return y;
}
int main() {
    int x = test(1);
    return x;
}
