//This file was automatically generated by allegro.
//Submit bug reports to https://github.com/UPWRD1/allegro

#include <stdio.h>

void test() {
    int y = 3;
}
int main() {
    bool x = true;
    return y;
}
