//This file was automatically generated by allegro.
//Submit bug reports to https://github.com/UPWRD1/allegro

#include <stdio.h>
#include <stdbool.h>

void printXNumTimes(char* x, int times) {
    int current = 0;
    while (current < times) {
        printf("%s\n", x);
        current = current + 1;
    }
 }

void main() {
    printXNumTimes("Hello world!", 4);
 }

