use crate::resource::rep::{
    common::{Spanned, Syntax},
    frontend::{
        ast::{ExprLit, Label, Untyped},
        cst::{CstExpr, Field, Pattern, UntypedCst},
    },
};
/// WARNING
/// Almost ALL the code in this file was generated by Claude.
/// Ideally, this will be completely rewritten in the future.
use itertools::Itertools;
use rustc_hash::{FxHashMap, FxHashSet};

// Pattern matching compiler — Rust port of the OCaml original.
//
// Compiles a list of typed patterns into a decision tree via
// a pattern matrix algorithm (similar to Maranget 2008).
// use std::collections::{HashMap, HashSet};

// ---------------------------------------------------------------------------
// Occurrences  (paths into the scrutinee)
// ---------------------------------------------------------------------------

/// A node in the occurrence tree that describes *where* a sub-value lives.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Occ {
    /// Root variable.
    Base,
    /// i-th projection of an occurrence.
    Proj(Box<Self>, Label),
    /// Unwrap the payload of a constructor at an occurrence.
    Unwrap(Box<Self>, Label, Option<<UntypedCst as Syntax>::Name>),
}

impl Occ {
    pub fn base(name: &Spanned<Box<CstExpr<UntypedCst>>>) -> Self {
        let _ = name;
        Self::Base
    }
}

// ---------------------------------------------------------------------------
// Patterns
// ---------------------------------------------------------------------------

impl<S: Syntax> Pattern<S> {
    pub fn wildcard() -> Self {
        Self::Any
    }

    pub fn is_wildcard(&self) -> bool {
        matches!(self, Self::Any | Self::Ident(_))
    }

    pub fn show(&self) -> String {
        match &self {
            Self::Any => "*".to_string(),
            Self::Ident(l) => l.to_string(),
            Self::Lit(v) => format!("{v:?}"),
            Self::VariantConstructor { name, value } => format!("{}", name.0),
            _ => todo!(),
        }
    }
}

// ---------------------------------------------------------------------------
// Pattern matrix
// ---------------------------------------------------------------------------

/// A pattern matrix: a rectangular grid of typed patterns plus, per row,
/// the index of the arm that should fire if the row matches.
#[derive(Debug, Clone)]
pub struct Matrix {
    /// Column headers — one occurrence per column.
    pub header: Vec<Occ>,
    /// Each row is `(patterns, arm_index)`.
    pub rows: Vec<(Vec<Pattern<UntypedCst>>, usize)>,
}

impl Matrix {
    pub fn new(header: Vec<Occ>) -> Self {
        Self {
            header,
            rows: vec![],
        }
    }

    pub fn is_empty(&self) -> bool {
        self.rows.is_empty()
    }

    pub fn num_cols(&self) -> usize {
        self.header.len()
    }

    /// Borrow the i-th row's pattern slice.
    pub fn row_pats(&self, i: usize) -> &[Pattern<UntypedCst>] {
        &self.rows[i].0
    }

    /// Swap columns `a` and `b` (header + every row).
    pub fn swap_columns(&mut self, a: usize, b: usize) {
        if a == b {
            return;
        }
        self.header.swap(a, b);
        for (row, _) in &mut self.rows {
            row.swap(a, b);
        }
    }

    /// Return the index of the first column whose patterns satisfy `pred`.
    pub fn find_first_column(&self, pred: impl Fn(&[Pattern<UntypedCst>]) -> bool) -> usize {
        for i in 0..self.num_cols() {
            let col: Vec<&_> = self.rows.iter().map(|(r, _)| &r[i]).collect();
            // Re-use pred with owned slice — collect to owned for simplicity.
            let owned: Vec<_> = col.into_iter().copied().collect();
            if pred(&owned) {
                return i;
            }
        }
        0
    }

    /// All patterns in column `col`.
    pub fn column(&self, col: usize) -> Vec<Pattern<UntypedCst>> {
        self.rows.iter().map(|(r, _)| r[col]).collect()
    }

    pub fn print(&self) -> String {
        let mut accum: String = String::new();
        for s in &self.header {
            accum = format!("{accum}{s:?},\t");
        }
        let len = accum.len();
        let divider = format!("{:-^1$}", "", len);
        accum = format!("{accum}\n{divider}\n");
        for (pat, _) in &self.rows {
            accum = format!("{accum}|{}\n", pat.iter().map(Pattern::show).join("\t|\t"));
        }
        accum
    }
}

// ---------------------------------------------------------------------------
// Decision tree
// ---------------------------------------------------------------------------
#[derive(Debug, Clone)]
pub enum DecisionTree {
    Fail,
    Leaf(usize),

    Switch {
        occ: Occ,
        cases: Vec<(Label, Self)>,
        default: Option<Box<Self>>,
    },
    IfEq {
        occ: Occ,
        lit: SigElem,
        then: Box<Self>,
        else_: Box<Self>,
    },
}

impl DecisionTree {
    /// Pretty-print the tree (mirrors the OCaml `Graphviz.print` hook).
    pub fn print(&self, indent: usize) {
        let pad = " ".repeat(indent * 2);
        match self {
            Self::Fail => println!("{pad}Fail"),
            Self::Leaf(i) => println!("{pad}Leaf({i})"),
            Self::Switch {
                occ,
                cases,
                default,
            } => {
                println!("{pad}Switch({occ:?})");
                for (ctor, sub) in cases {
                    println!("{pad}  | {} =>", ctor.0.0);
                    sub.print(indent + 2);
                }
                if let Some(def) = default {
                    println!("{pad}  | _ =>");
                    def.print(indent + 2);
                }
            }
            Self::IfEq {
                occ,
                lit,
                then,
                else_,
            } => {
                println!("{pad}if {occ:?} == {}", lit.print());
                println!("{pad}  then ");
                then.print(indent + 2);

                println!("{pad}  else");
                else_.print(indent + 2);
            }
        }
    }
}

fn occurrences_of(p: &Pattern<UntypedCst>, base: &Occ) -> Vec<(Occ, Pattern<UntypedCst>)> {
    match &p {
        Pattern::ProductConstructor { fields } => fields
            .iter()
            .enumerate()
            .map(|(i, sub_p)| match sub_p {
                Field::Def(field_def) => todo!(),
                Field::Macro(field_macro) => todo!(),
                Field::Inherit(name) => {
                    let occ = Occ::Proj(Box::new(base.clone()), *name);
                    (occ, Pattern::Ident(Untyped(name.0)))
                }
            })
            .collect(),
        // Pattern::Record { fields, open }
        _ => vec![(base.clone(), *p)],
    }
} // ---------------------------------------------------------------------------
// preprocess: build the initial matrix from a flat list of patterns
// ---------------------------------------------------------------------------

/// Expand each top-level pattern into a map `Occ → Pattern<_>`, unfolding tuples
/// into their projections, then assemble a `Matrix`.
///
/// `res` maps a row index (0-based) to its arm index.
pub fn preprocess(base: &Occ, ps: &[Pattern<UntypedCst>], res: impl Fn(usize) -> usize) -> Matrix {
    // Build the header (ordered, deduplicated list of occurrences).
    let mut seen: Vec<Occ> = Vec::new();
    let mut header: Vec<Occ> = Vec::new();
    let all_pairs: Vec<Vec<(Occ, Pattern<_>)>> = ps
        .iter()
        .map(|p| {
            let pairs = occurrences_of(p, base);
            for (occ, _) in &pairs {
                if !seen.contains(occ) {
                    seen.push(occ.clone());
                    header.push(occ.clone());
                }
            }
            pairs
        })
        .collect();

    // Populate rows.
    let mut matrix = Matrix::new(header.clone());
    for (i, pairs) in all_pairs.into_iter().enumerate() {
        let map: FxHashMap<_, _> = pairs.into_iter().collect();
        let row: Vec<Pattern<_>> = header
            .iter()
            .map(|occ| map.get(occ).copied().unwrap_or(Pattern::Any))
            .collect();
        matrix.rows.push((row, res(i)));
    }
    matrix
}

// ---------------------------------------------------------------------------
// specialise: filter + transform rows for a specific head constructor
// ---------------------------------------------------------------------------

/// Strip the first column from every row whose head pattern satisfies
/// `pred`, unwrap the payload (if any), and re-preprocess the result.
/// The remaining columns are reattached afterwards.
fn specialise(matrix: &Matrix, pred: impl Fn(&Pattern<UntypedCst>) -> bool) -> Matrix {
    let mut patterns: Vec<Pattern<_>> = Vec::new();
    let mut indices: Vec<usize> = Vec::new();
    let mut remainders: Vec<Vec<Pattern<_>>> = Vec::new();

    for (row, idx) in &matrix.rows {
        let head = &row[0];
        if pred(head) {
            let unwrapped = unwrap_payload(*head);
            patterns.push(unwrapped);
            indices.push(*idx);
            remainders.push(row[1..].to_vec());
        }
    }

    // let occ = Occ::Unwrap(Box::new(matrix.header[0].clone()));

    let occ = matrix.header[0].clone();

    // Re-run preprocessing on the unwrapped payloads.
    let idx_snapshot = indices.clone();
    let mut m2 = preprocess(&occ, &patterns, move |i| idx_snapshot[i]);

    // Append the tail columns from the original header.
    for h in &matrix.header[1..] {
        m2.header.push(h.clone());
    }

    // Append the remainder columns to each row.
    for (i, (row, _)) in m2.rows.iter_mut().enumerate() {
        if let Some(rem) = remainders.get(i) {
            row.extend_from_slice(rem);
        }
    }

    m2
}

fn specialise_label(matrix: &Matrix, label: Label) -> Matrix {
    let mut patterns: Vec<Pattern<_>> = Vec::new();
    let mut indices: Vec<usize> = Vec::new();
    let mut remainders: Vec<Vec<Pattern<_>>> = Vec::new();

    for (row, idx) in &matrix.rows {
        let head = &row[0];
        match head {
            Pattern::VariantConstructor { name, value } if (*name == label) => {
                let unwrapped = unwrap_payload(*head);
                patterns.push(unwrapped);
                indices.push(*idx);
                if let Some(value) = value {
                    remainders.push(vec![*value.0])
                };
                remainders.push(row[1..].to_vec());
            }
            _ => {}
        }
    }

    let occ = Occ::Unwrap(Box::new(matrix.header[0].clone()), label, None);

    // let occ = matrix.header[0].clone();

    // Re-run preprocessing on the unwrapped payloads.
    let idx_snapshot = indices.clone();
    let mut m2 = preprocess(&occ, &patterns, move |i| idx_snapshot[i]);

    // Append the tail columns from the original header.
    for h in &matrix.header[1..] {
        m2.header.push(h.clone());
    }

    // Append the remainder columns to each row.
    for (i, (row, _)) in m2.rows.iter_mut().enumerate() {
        if let Some(rem) = remainders.get(i) {
            row.extend_from_slice(rem);
        }
    }

    m2
}

/// Unwrap the payload of a constructor pattern.
/// Sets `ty_out` to the payload's type on the first call.
fn unwrap_payload(p: Pattern<UntypedCst>) -> Pattern<UntypedCst> {
    match p {
        Pattern::VariantConstructor { name, value } => {
            *value
                .unwrap_or(name.0.convert(Pattern::Lit(ExprLit::Unit)))
                .0
        }
        Pattern::Lit(_) => Pattern::Any,
        _ => p,
    }
}

// ---------------------------------------------------------------------------
// Helper predicates
// ---------------------------------------------------------------------------

/// Does pattern `p` admit constructor `c`?\
/// (Wildcards / variables admit everything.)
fn admits(c: &SigElem, p: &Pattern<UntypedCst>) -> bool {
    match c {
        SigElem::Label(c) => match &p {
            Pattern::VariantConstructor { name: c2, .. } => c == c2,
            Pattern::Any | Pattern::Ident(_) => true,
            _ => false,
        },
        SigElem::Lit(l1) => match &p {
            Pattern::Lit(l2) => l1 == l2,
            Pattern::Any | Pattern::Ident(_) => true,
            _ => false,
        },

        _ => todo!("{c:?}, {p:?}"),
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SigElem {
    Label(Label),
    Lit(ExprLit),
    Var(Untyped),
}

impl SigElem {
    fn print(&self) -> String {
        match self {
            Self::Label(label) => label.0.0.to_string(),
            Self::Lit(l) => format!("{l:?}"),
            Self::Var(v) => format!("{}", v.0),
        }
    }
}

/// Collect every constructor name mentioned in a column.
fn collect_signature(ps: Vec<Pattern<UntypedCst>>) -> FxHashSet<SigElem> {
    let mut accum = FxHashSet::default();
    let mut worklist = ps;
    while let Some(p) = worklist.pop() {
        if let Some(sigelem) = {
            match &p {
                Pattern::VariantConstructor { name, value } => {
                    if let Some(value) = value {
                        worklist.push(*value.0)
                    };
                    Some(SigElem::Label(*name))
                }
                Pattern::Lit(f) => Some(SigElem::Lit(*f)),
                Pattern::Ident(x) => Some(SigElem::Var(*x)),
                _ => None,
            }
        } {
            accum.insert(sigelem);
        }
    }
    accum
}

/// True iff any pattern in the slice is refutable.
fn has_refutable(ps: &[Pattern<UntypedCst>]) -> bool {
    ps.iter().any(Pattern::is_refutable)
}

// ---------------------------------------------------------------------------
// compile: entry point
// ---------------------------------------------------------------------------

/// Compile `ps` (one per arm, 0-indexed) into a `DecisionTree`.
pub fn compile(ps: &[Pattern<UntypedCst>]) -> DecisionTree {
    let initial = preprocess(&Occ::Base, ps, |i| i);
    compile_matrix(initial)
}

fn compile_matrix(matrix: Matrix) -> DecisionTree {
    println!("{}", matrix.print());
    // Base case 1: no rows → no match.
    if matrix.is_empty() {
        return DecisionTree::Fail;
    }

    // Base case 2: first row is all wildcards → it fires unconditionally.
    if matrix.row_pats(0).iter().all(Pattern::is_irrefutable) {
        return DecisionTree::Leaf(matrix.rows[0].1);
    }

    // Recursive case: choose the first column with a refutable pattern,
    // swap it to position 0, then case-split on its constructor signature.
    let mut matrix = matrix;
    let col_idx = matrix.find_first_column(has_refutable);
    matrix.swap_columns(0, col_idx);

    let first_col = matrix.column(0);
    let signature = collect_signature(first_col);
    dbg!(&signature);
    let occ = matrix.header[0].clone();
    let default_tree = {
        let sub = specialise(&matrix, Pattern::is_wildcard);
        if sub.is_empty() {
            DecisionTree::Fail
        } else {
            compile_matrix(sub)
        }
    };
    dbg!(&matrix);

    // Split signature by kind
    let labels: Vec<_> = signature
        .iter()
        .filter_map(|s| match s {
            SigElem::Label(l) => Some(l),
            _ => None,
        })
        .collect();

    let lits: Vec<_> = signature
        .iter()
        .filter(|s| matches!(s, SigElem::Lit(_)))
        .collect();

    if lits.is_empty() {
        // Pure enum switch — existing logic
        DecisionTree::Switch {
            occ,
            cases: labels
                .into_iter()
                .map(|l| {
                    let sub = specialise_label(&matrix, *l);
                    (*l, compile_matrix(sub))
                })
                .collect(),
            default: Some(Box::new(default_tree)),
        }
    } else {
        // Fold literals into a chain of IfEq, innermost else = default
        lits.iter().rfold(default_tree, |else_branch, lit| {
            let sub = specialise(&matrix, |p| admits(lit, p));
            DecisionTree::IfEq {
                occ: occ.clone(),
                lit: **lit,
                then: Box::new(compile_matrix(sub)),
                else_: Box::new(else_branch),
            }
        })
    }
}
